
DROP DATABASE IF EXISTS Bamazon;

CREATE DATABASE Bamazon;

USE DATABASE Bamazon;

CREATE TABLE products (
id INTEGER(11) AUTO_INCREMENT NOT NULL,
product_name VARCHAR(30) NOT NULL,
department VARCHAR(30) NOT NULL,
cost DECIMAL(10,2) NOT NULL,
stock INTEGER(11) NOT NULL,
PRIMARY KEY (id)
);